### ISSUE TITLE
Issue with latest release

### ISSUE THREAD

**Issue by Grinnz** [perl5-dbi/DBD-mysql#233]
The latest release has some issues: https://metacpan.org/release/CAPTTOFU/DBD-mysql-4.045

The included META files indicate a distribution version of 4.044 (a version that already exists) even though DBD::mysql's version was updated, indicating they were not properly generated. https://metacpan.org/source/CAPTTOFU/DBD-mysql-4.045/META.json#L65

Also, the release was not indexed in PAUSE (https://cpanmeta.grinnz.com/packages#=DBD::mysql) possibly because of the previous issue, but the email you got from PAUSE would have more details.

**Comment by CaptTofu** [comment]
hey there - I just fixed an issue with ExtUtils::MakeMaker and re-created the distribution archive, though forgotten you can't use the same filename. I have uploaded a new archive, but named it DBD-mysql-4.045_1.tar.gz. Is this how you deal with a previously-broken upload?

**Comment by Grinnz** [comment]
A tarball with an underscore in the name will be considered a trial release so won't be indexed. You could simply use a hyphen or something instead but I would recommend a clean version bump to avoid confusion since you already have a release with the module version 4.045.

**Comment by mbeijen** [comment]
No, you should update $VERSION to 4.046, update changes file, tag in git,
make clean, make dist, verify the tarball & upload to PAUSE.

_01 numbers are treated by CPAN as 'test' releases and will not be
considered if you type 'cpan install My::Module'

Op 8 feb. 2018 21:34 schreef "Patrick Galbraith" <notifications@github.com>:

hey there - I just fixed an issue with ExtUtils::MakeMaker and re-created
the distribution archive, though forgotten you can't use the same filename.
I have uploaded a new archive, but named it DBD-mysql-4.045_1.tar.gz. Is
this how you deal with a previously-broken upload?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/perl5-dbi/DBD-mysql/issues/233#issuecomment-364239914>,
or mute the thread

**Comment by Grinnz** [comment]
4.046 was indexed: https://cpanmeta.grinnz.com/packages#=DBD::mysql and appears to have correct version numbers. Closing
