### ISSUE TITLE
Broken mysql_skip_secure_auth support

### ISSUE THREAD

**Issue by cejkar** [perl5-dbi/DBD-mysql#249]
Please return #define SECURE_AUTH_LAST_VERSION 50704 to dbdimp.h removed by d6a114ce157e197ab266360c6faf4dcc2ef9f7c3, probably by an accident. And please change undefined LIBMYSQL_VERSION_ID to MYSQL_VERSION_ID added to dbdimp.c by 7bc0de70aa1e6a3e16fdfe8c83e6c704b5431aa1.

If you like, you can also fix #if LIBMYSQL_VERSION_ID >= LIBMYSQL_FABRIC_VERSION && LIBMYSQL_VERSION_ID <= LIBMYSQL_LAST_FABRIC_VERSION in dbdimp.h, where are another two occurences of undefined LIBMYSQL_VERSION_ID.

**Comment by pali** [comment]
This problem should be already fixed in DBD::MariaDB:

https://github.com/gooddata/DBD-MariaDB/commit/4c452379caa16359b5b94943892b5d658c0a13f9

https://github.com/gooddata/DBD-MariaDB/blob/a83dc2919c32f3648ef9d51033bd8b056b41a5ef/dbdimp.c#L1979-L1997

https://github.com/gooddata/DBD-MariaDB/blob/master/dbdimp.h#L301-L304

Note that check for fabric via LIBMYSQL_VERSION_ID is valid as fabric support is only in connector/c which set that special LIBMYSQL_VERSION_ID define.

**Comment by srchulo** [comment]
Any chance this can be fixed? Using DBD::MariaDB with `mariadb_skip_secure_auth `works, but it would be nice to be able to use the same driver in all places.

**Comment by dveeden** [comment]
The code in master that relates to this has been simplified, which fixes this issue.
