### ISSUE TITLE
Can't install DBD::mysqlx missing xapi.h

### ISSUE THREAD

**Issue by geekdad1** [perl5-dbi/DBD-mysql#453]
### DBD::mysql version

mysqlx-0.003

### Server version

8.0.39

### Operating system version

Windows Server 2022

### What happened?

Strawberry perl trying to install using the CPAN version. Get the following error 

gcc -c  -IC:\Strawberry\perl\site\lib\auto\DBI -I/usr/include/mysql-cppconn-8 -std=gnu99 -std=c99 -DWIN32 -DWIN64 -DPERL_TEXTMODE_SCRIPTS -DMULTIPLICITY -DPERL_IMPLICIT_SYS -DUSE_PERLIO -D__USE_MINGW_ANSI_STDIO -fwrapv -fno-strict-aliasing -mms-bitfields -Os -falign-functions -falign-jumps -falign-labels -falign-loops -freorder-blocks -freorder-blocks-algorithm=stc -freorder-blocks-and-partition   -DVERSION=\"0.003\" -DXS_VERSION=\"0.003\"  "-IC:\STRAWB~1\perl\lib\CORE"   dbdimp.c
In file included from dbdimp.c:10:
dbdimp.h:10:10: fatal error: mysqlx/xapi.h: No such file or directory
   10 | #include <mysqlx/xapi.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
g

**Comment by dveeden** [comment]
This looks like an issue for [DBD::mysqlx](https://github.com/dveeden/DBD-mysqlx), not DBD::mysql. 

Note that DBD::mysqlx was an experiment which I stopped working on because of a lack of time etc. Because of that the repo has been archived.

DBD::mysqlx was using the X Protocol instead of the classic MySQL Protocol and was build on top of the C API of MySQL Connector/C++ instead of libmysqlclient, like DBD::mysql is.
